[phases.setup]
nixPkgs = ["python3", "postgresql_16", "gcc"]

[phases.install]
cmds = [
  "python -m venv --copies /opt/venv",
  "/opt/venv/bin/pip install -r myproject/requirements.txt"
]

[phases.build]
cmds = [
  "/opt/venv/bin/python manage.py collectstatic --noinput",
  "/opt/venv/bin/python manage.py migrate"
]

[phases.start]
cmd = "gunicorn myproject.wsgi:application --chdir myproject --bind 0.0.0.0:$PORT"
