[phases.setup]
nixPkgs = ["python312", "postgresql_16", "gcc"]

[phases.install]
cmds = [
  "python -m venv --copies /opt/venv",
  "/opt/venv/bin/pip install --upgrade pip",
  "/opt/venv/bin/pip install --force-reinstall -r myproject/requirements.txt",
  "/opt/venv/bin/pip show gunicorn"
]


[phases.build]
cmds = [
  "/opt/venv/bin/python myproject/manage.py collectstatic --noinput"
]

[phases.start]
cmd = "/opt/venv/bin/python myproject/manage.py migrate && /opt/venv/bin/gunicorn myproject.wsgi:application --chdir myproject --bind 0.0.0.0:$PORT"
