[phases.setup]
nixPkgs = ["python3", "postgresql_16", "gcc"]

[phases.build]
cmds = [
  "/opt/venv/bin/python manage.py collectstatic --noinput",
  "/opt/venv/bin/python manage.py migrate"
]


[phases.build]
cmds = [
  ". /opt/venv/bin/activate",
  "python manage.py collectstatic --noinput",
  "python manage.py migrate"
]

[phases.start]
cmd = "gunicorn myproject.wsgi:application --chdir myproject --bind 0.0.0.0:$PORT"
