[phases.setup]
nixPkgs = ["python3", "postgresql_16.dev", "gcc"]

[phases.install]
cmds = [
  "python -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install -r myproject/requirements.txt"
]

[phases.build]
cmds = [
  ". /opt/venv/bin/activate",
  "python myproject/manage.py collectstatic --noinput",
  "python myproject/manage.py migrate"
]

[phases.start]
cmd = "gunicorn myproject.wsgi:application --chdir myproject --bind 0.0.0.0:$PORT"
[phases.setup]
nixPkgs = ["python3", "postgresql_16.dev", "gcc"]

[phases.install]
cmds = [
  "python -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install -r myproject/requirements.txt"
]

[phases.build]
cmds = [
  ". /opt/venv/bin/activate",
  "python myproject/manage.py collectstatic --noinput",
  "python myproject/manage.py migrate"
]

[phases.start]
cmd = "gunicorn myproject.wsgi:application --chdir myproject --bind 0.0.0.0:$PORT"
