# Generated by Django 5.2.1 on 2025-05-29 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_rename_shipping_user_shippingaddress_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='user',
            new_name='shipping_user',
        ),
    ]
