# Generated by Django 5.2.1 on 2025-05-29 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_order_order_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipping_adddress',
            new_name='shipping_address',
        ),
        migrations.RenameField(
            model_name='order_items',
            old_name='Order',
            new_name='order',
        ),
    ]
