# Generated by Django 5.2.1 on 2025-05-30 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_rename_user_order_shi_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shi',
            new_name='user',
        ),
    ]
