# Generated by Django 5.2.1 on 2025-05-30 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_rename_shi_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='shipping_full_name',
            new_name='shipping_name',
        ),
    ]
