# Generated by Django 5.2.1 on 2025-05-30 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_rename_shipping_full_name_shippingaddress_shipping_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='shipping_name',
            new_name='shipping_full_name',
        ),
    ]
