# Generated by Django 5.2.1 on 2025-05-30 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_rename_shipping_name_shippingaddress_shipping_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipped',
            field=models.BooleanField(default=False),
        ),
    ]
